version: '3.9'

services:
  app:
    image: 'les4:latest'
    build: .
#      context: .
    container_name: applesson
    working_dir: /usr/src/myapp
    ports:
    - "8080:8080"
    depends_on:
      - dblesson
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dblesson:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678

  dblesson:
    image: 'postgres:latest'
    container_name: dblesson
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678